frequency: 20
delay: 0.0
magnetic_declination_radians: 0.0
yaw_offset: 0.0
zero_altitude: true
publish_filtered_gps: false
use_odometry_yaw: false
wait_for_datum: false

datum: [22.580768, 120.296145, 0.0]
